//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int Id { get; set; }
        public string nome_paciente { get; set; }
        public System.DateTime dia { get; set; }
        public System.DateTime hora { get; set; }
        public string especialidade { get; set; }
        public int MedicoId { get; set; }
    
        public virtual Medico Medico { get; set; }
    }
}
